cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.urls import path
from myshop.views import get_main, get_category, get_product

urlpatterns = [
    path('', get_main, name='main'),
    path('category/<int:pk>/', get_category, name='category_list'),
    path('product/<int:pk>/', get_product, name='product_detail'),
    # path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('myshop.urls')),
]

myshop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("name",)
        verbose_name = "Category"
        verbose_name_plural = "Categories"

class Product(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    time_add = models.TimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("name",)
        verbose_name = "Product"
        verbose_name_plural = "Products"
        index_together = (('id', 'slug'),)


class Photo(models.Model):
    name = models.CharField(max_length=40)
    image = models.ImageField(upload_to="images")
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

myshop/views.py
from django.shortcuts import render
from myshop.models import Category, Product, Photo
from cart.forms import CartAddProductForm

def get_main(request):
    categories = Category.objects.all()
    new_products = Product.objects.all().order_by("-time_add")[:5]
    return render(request, 'shophtml/main.html',
                  {'categories':categories, "new_products":new_products})

def get_category(request, pk):
    category = Category.objects.get(pk=pk)
    products = category.product_set.all()
    categories = Category.objects.all()
    return render(request, 'shophtml/category.html',
                  {'category': category, "products": products, "categories":categories})

def get_product(request, pk):
    product = Product.objects.get(pk=pk)
    categories = Category.objects.all()
    cart_product_form = CartAddProductForm()
    return render(request, 'shophtml/product.html',
                  {"product": product, "categories": categories, 'cart_product_form': cart_product_form})

myshop/templates/shophtml/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}Anime Shop{% endblock %}</title>
<!--    <link href="{% static "css/base.css" %}" rel="stylesheet">-->
  </head>
  <body>
    <div>

        <div id="header">
            <a href="/">Anime Shop</a>
        </div>

        <div>
            Search
        </div>

        <div>
            {% with total_items=cart|length %}
            {% if cart|length > 0 %}
            Your cart:
            <a href="{% url "cart:cart_detail" %}">
            {{ total_items }} item{{ total_items|pluralize }},
            ${{ cart.get_total_price }}
            </a>
            {% else %}
            Your cart is empty.
            {% endif %}
            {% endwith %}
        </div>

    </div>

    <div>
        {% for category in categories %}
        <a href="{% url "category_list" category.pk %}">{{ category.name }}</a>
        {% endfor %}
    </div>

    <div id="subheader">
      Photo will be here
    </div>

    <div id="mycontent">
      {% block content %}{% endblock %}
    </div>

    <div id="content">
    </div>

  </body>
</html>

myshop/templates/shophtml/category.html
{% extends "shophtml/base.html" %}
{% load static %}


{% block title %}
  {{ category.name }}
{% endblock %}

{% block content %}
  {% for product in products %}
    <div>
      <div>
        <a href="{% url "product_detail" product.pk %}">{{ product.name }}</a>
      </div>
      <div>
        {{ product.price }} BYN
      </div>
    </div>

  {% endfor %}
{% endblock %}

myshop/templates/shophtml/main.html
{% extends "shophtml/base.html" %}
{% load static %}

{% block content %}

    <div>
        News will be here soon!!!

    </div>

    <div>
        {% for product in new_products %}
        <div>
        {{ product.name }}
        {{ product.price }} BYN
        </div>
        {% endfor %}
    </div>

{% endblock %}

myshop/templates/shophtml/product.html
{% extends "shophtml/base.html" %}
{% load static %}


{% block title %}
  {{ product.slug }}
{% endblock %}

{% block content %}
    <div>
      <div>
        {{ product.name }}
      </div>
      <div>
        {{ product.price }} BYN
      </div>
      <div>
        <form action="{% url "cart:cart_add" product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Add to cart">
        </form>
      </div>
      <div>
        {{ product.description }}
        {% for image in product.photo_set.all %}
        <img src="{{ images.image.url }}"  alt="Photo will be here">
        {% endfor %}

      </div>
    </div>

{% endblock %}